=== GoogleCloudPlatform/datashare-toolkit/entitlements/bqdsEntitlements/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "/BQDSConfiguration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "schemaVersion": {
      "type": "string"
    },
    "projectId": {
      "type": "string"
    },
    "accessControl": {
      "$ref": "#/definitions/configAccessControl"
    },
    "groups": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/group"
      },
      "uniqueItems": true
    },
    "datasets": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/dataset"
      },
      "uniqueItems": true
    },
    "views": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/view"
      },
      "uniqueItems": true
    }
  },
  "required": [
    "name",
    "projectId",
    "datasets",
    "views"
  ],
  "definitions": {
    "dataset": {
      "id": "/dataset",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "maxLength": 1024
        },
        "accessControlLabels": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "groupNames": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "access": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/access"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "name"
      ]
    },
    "access": {
      "id": "/access",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "userByEmail": {
          "type": "string",
          "format": "email"
        },
        "groupByEmail": {
          "type": "string",
          "format": "email"
        },
        "domain": {
          "type": "string"
        },
        "specialGroup": {
          "type": "string"
        },
        "iamMember": {
          "type": "string"
        }
      },
      "oneOf": [
        {
          "required": [
            "userByEmail"
          ]
        },
        {
          "required": [
            "groupByEmail"
          ]
        },
        {
          "required": [
            "domain"
          ]
        },
        {
          "required": [
            "specialGroup"
          ]
        },
        {
          "required": [
            "iamMember"
          ]
        }
      ]
    },
    "group": {
      "id": "/group",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "access": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/access"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "name",
        "access"
      ]
    },
    "view": {
      "id": "/view",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "maxLength": 1024
        },
        "datasetNames": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 1024
          },
          "uniqueItems": true
        },
        "source": {
          "$ref": "#/definitions/source"
        },
        "custom": {
          "$ref": "#/definitions/custom"
        },
        "expiration": {
          "$ref": "#/definitions/expiration"
        }
      },
      "required": [
        "name",
        "datasetNames"
      ]
    },
    "expiration": {
      "id": "/expiration",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "delete": {
          "type": "boolean"
        },
        "time": {
          "type": "integer"
        }
      },
      "required": [
        "time"
      ]
    },
    "publicAccess": {
      "id": "/publicAccess",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "queryFilter": {
          "type": "string"
        },
        "limit": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "enabled",
        "queryFilter"
      ]
    },
    "source": {
      "id": "/source",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "datasetId": {
          "type": "string",
          "maxLength": 1024
        },
        "tableId": {
          "type": "string",
          "maxLength": 1024
        },
        "visibleColumns": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 128
          },
          "uniqueItems": true
        },
        "hiddenColumns": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 128
          },
          "uniqueItems": true
        },
        "queryFilter": {
          "type": "string"
        },
        "publicAccess": {
          "$ref": "#/definitions/publicAccess"
        },
        "accessControl": {
          "$ref": "#/definitions/sourceAccessControl"
        }
      },
      "required": [
        "datasetId",
        "tableId"
      ]
    },
    "sourceAccessControl": {
      "id": "/sourceAccessControl",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "datasetEnabled": {
          "type": "boolean"
        },
        "labelColumn": {
          "type": "string",
          "maxLength": 128
        },
        "labelColumnDelimiter": {
          "type": "string"
        },
        "labels": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "labelColumn"
      ]
    },
    "custom": {
      "id": "/custom",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "query": {
          "type": "string"
        },
        "authorizeFromDatasetIds": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 1024
          },
          "uniqueItems": true
        }
      },
      "required": [
        "query"
      ]
    },
    "configAccessControl": {
      "id": "/configAccessControl",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "datasetId": {
          "type": "string",
          "maxLength": 1024
        },
        "viewId": {
          "type": "string",
          "maxLength": 1024
        }
      },
      "required": [
        "datasetId",
        "viewId"
      ]
    }
  }
}

=== GoogleCloudPlatform/datashare-toolkit/examples/mlb/config/entitlements/complex.json
{
  "name": "mlb_complex",
  "projectId": "cds-ci",
  "accessControl": {
    "datasetId": "access_control",
    "viewId": "groupEntities"
  },
  "groups": [{
      "name": "newyork_users",
      "access": [{
        "userByEmail": "benjentargaryen.327201@gmail.com"
      }]
    },
    {
      "name": "chicago_users",
      "access": [{
        "userByEmail": "melisandresnow.388027@gmail.com"
      }]
    }
  ],
  "datasets": [{
      "name": "ny_fans_c",
      "groupNames": [
        "newyork_users"
      ]
    },
    {
      "name": "chicago_fans_c",
      "groupNames": [
        "chicago_users"
      ]
    }
  ],
  "views": [{
      "datasetNames": [
        "ny_fans_c"
      ],
      "name": "home_game_logs",
      "custom": {
        "query": "select game_date, v_name, v_game_number, h_name, h_game_number, sum(v_hits) as v_hits, sum(h_hits) as h_hits\nfrom `${projectId}.mlb.game_logs`\ngroup by game_date, v_name, v_game_number, h_name, h_game_number\nhaving v_hits = 0 or h_hits = 0",
        "authorizeFromDatasetIds": [
          "mlb"
        ]
      }
    },
    {
      "datasetNames": [
        "chicago_fans_c"
      ],
      "name": "away_game_logs",
      "custom": {
        "query": "select game_date, v_name, v_game_number, h_name, h_game_number, sum(v_hits) as v_hits, sum(h_hits) as h_hits\nfrom `${projectId}.mlb.game_logs`\ngroup by game_date, v_name, v_game_number, h_name, h_game_number\nhaving v_hits = 0 or h_hits = 0",
        "authorizeFromDatasetIds": [
          "mlb"
        ]
      }
    },
    {
      "datasetNames": [
        "ny_fans_c",
        "chicago_fans_c"
      ],
      "name": "aggregated_scores",
      "custom": {
        "query": "with scores as (\n  SELECT\n    h_name as team_abbrev,\n    sum(h_score) as score,\n    sum(h_game_number) as game_number,\n    count(distinct concat(cast(game_date as string), cast(h_game_number as string), h_name)) as number_of_games\n  FROM `${projectId}.mlb.game_logs`\n  group by h_name\n  union all\n  SELECT\n    v_name,\n    sum(v_score),\n    sum(v_game_number),\n    count(distinct concat(cast(game_date as string), cast(v_game_number as string), v_name))\n  FROM `${projectId}.mlb.game_logs`\n  group by v_name\n),\nteam_scores as (\n  select\n    t.team_name,\n    `from`,\n    `to`, \n    sum(s.score) as score,\n    number_of_games,\n    case when `to` - `from` = 0 then 1 else `to` - `from` end as years_active\n  from scores s\n  join `${projectId}.mlb.teams` t on s.team_abbrev = t.abbrev\n  group by t.team_name, `from`, `to`, number_of_games\n)\nselect\n  team_name,\n  `from`,\n  `to`,\n  score,\n  years_active,\n  score / years_active as avg_runs_per_year\nfrom team_scores\norder by avg_runs_per_year desc",
        "authorizeFromDatasetIds": [
          "mlb"
        ]
      }
    }
  ]
}

=== GoogleCloudPlatform/datashare-toolkit/examples/MLB/config/simple.json
{
  "name": "mlb_simple",
  "projectId": "sferrazza-cloud-sandbox",
  "accessControl": {
    "datasetId": "access_control",
    "viewId": "groupEntities"
  },
  "groups": [{
      "name": "newyork_users",
      "access": [{
        "userByEmail": "benjentargaryen.327201@gmail.com"
      }]
    },
    {
      "name": "chicago_users",
      "access": [{
        "userByEmail": "melisandresnow.388027@gmail.com"
      }]
    }
  ],
  "datasets": [{
      "name": "ny_fans",
      "groupNames": [
        "newyork_users"
      ],
      "accessControlLabels": [
        "NY1",
        "NY2",
        "NY3",
        "NY4",
        "NYA",
        "NYN",
        "NYP"
      ]
    },
    {
      "name": "chicago_fans",
      "groupNames": [
        "chicago_users"
      ]
    }
  ],
  "views": [{
      "datasetNames": [
        "ny_fans"
      ],
      "name": "ny_game_logs",
      "expiration": {
        "delete": true,
        "time": 1597944246000
      },
      "source": {
        "datasetId": "mlb",
        "tableId": "game_logs",
        "accessControl": {
          "enabled": true,
          "datasetEnabled": false,
          "labelColumn": "label",
          "labelColumnDelimiter": "|"
        },
        "publicAccess": {
          "enabled": true,
          "queryFilter": "h_game_number = 1 or v_game_number = 1",
          "limit": 20
        }
      }
    },
    {
      "datasetNames": [
        "chicago_fans"
      ],
      "name": "chicago_game_logs",
      "source": {
        "datasetId": "mlb",
        "tableId": "game_logs",
        "accessControl": {
          "enabled": true,
          "datasetEnabled": false,
          "labelColumn": "label",
          "labels": [
            "CH1",
            "CH2",
            "CHA",
            "CHF",
            "CHN",
            "CHP",
            "CHU"
          ]
        }
      }
    }
  ]
}
